server:
  port: 8080
  servlet:
    context-path: /budgets-api
    session:
      cookie:
        path: /budgets-api
spring:
  profiles:
    active: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: budgets